"use client";

import { useEffect, useState, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { RefreshCw, Sparkles } from "lucide-react";
import { API_URL } from "@/lib/api";

interface RecommendationsPanelProps {
  /** GitHub username to generate recommendations for. */
  username: string;
  /** Number of days of history to analyse. */
  days: number;
}

interface RecommendationsResponse {
  recommendations: string;
  generated_at: string;
}

/**
 * Displays AI-generated proactive recommendations for a user's GitHub activity.
 *
 * Fetches from POST /insights/recommendations on mount and on username/days changes.
 * Provides a refresh button to re-trigger generation.
 *
 * @param username - GitHub username.
 * @param days - Analysis window in days.
 */
export function RecommendationsPanel({ username, days }: RecommendationsPanelProps) {
  const [recommendations, setRecommendations] = useState<string | null>(null);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchRecommendations = useCallback(async () => {
    if (!username) return;
    setLoading(true);
    setError(null);

    try {
      const res = await fetch(`${API_URL}/insights/recommendations`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username, days }),
      });

      if (!res.ok) {
        throw new Error(`Request failed with status ${res.status}`);
      }

      const data = (await res.json()) as RecommendationsResponse;
      setRecommendations(data.recommendations);
      setGeneratedAt(data.generated_at);
    } catch (err: unknown) {
      const e = err as Error;
      setError(e.message || "Failed to load recommendations");
    } finally {
      setLoading(false);
    }
  }, [username, days]);

  useEffect(() => {
    fetchRecommendations();
  }, [fetchRecommendations]);

  return (
    <Card className="bg-black/40 border-l-2 border-l-emerald-500 border-zinc-800">
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-3">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-emerald-400" />
            <CardTitle className="text-sm font-semibold text-emerald-300">AI Insights</CardTitle>
          </div>
          <CardDescription className="text-xs text-zinc-500">
            Generated by Groq LLaMA 3.3
          </CardDescription>
        </div>
        <button
          id="recommendations-refresh-btn"
          onClick={fetchRecommendations}
          disabled={loading}
          aria-label="Refresh AI recommendations"
          className="text-zinc-500 hover:text-emerald-400 transition-colors disabled:opacity-40"
        >
          <RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />
        </button>
      </CardHeader>

      <CardContent>
        {loading && !recommendations && (
          <div className="space-y-2 animate-pulse" aria-label="Loading recommendations">
            <div className="h-3 bg-zinc-800 rounded w-3/4" />
            <div className="h-3 bg-zinc-800 rounded w-full" />
            <div className="h-3 bg-zinc-800 rounded w-5/6" />
          </div>
        )}

        {error && !loading && (
          <p className="text-xs text-zinc-500 italic">
            Recommendations unavailable — {error}
          </p>
        )}

        {recommendations && !error && (
          <div className="text-sm text-zinc-300 whitespace-pre-wrap leading-relaxed prose prose-invert prose-sm max-w-none">
            {recommendations}
          </div>
        )}

        {generatedAt && !loading && (
          <p className="text-[10px] text-zinc-600 mt-3">
            Last generated:{" "}
            {new Date(generatedAt).toLocaleString(undefined, {
              dateStyle: "medium",
              timeStyle: "short",
            })}
          </p>
        )}
      </CardContent>
    </Card>
  );
}
