import logging
import json
import groq
import os

logger = logging.getLogger(__name__)

# LLM Context Window Constraints
MAX_COMMITS_PER_REPO = 50
MAX_MESSAGE_LENGTH = 300

def format_commits (commits:list) -> dict:
    """
    Receives a FLAT LIST of commit dicts (generated by  repo_reader.get_commits) 
    and then groups by repo, cleans messages -> returns dict
    
    Args: 
        commits (list): List of commit dicts that needs to be formatted

    Returns:
        dict object containing the cleaned commit information which will be used 
        for generating prompt and further summarize
    """
    formatted_commits_grouped = {}

    if not commits:
        logger.warning("format_commits: No commits to format")
        return {}

    for commit in commits:
        repo = commit["repo"]
        short_hash = commit["hash"][:7]
        date = commit["date"].strftime("%Y-%m-%d")

        clean_message = " | ".join(line.strip() for line in commit["message"].splitlines() if line.strip())
        
        # Truncate extremely long messages to prevent token overflow/injection
        if len(clean_message) > MAX_MESSAGE_LENGTH:
            clean_message = clean_message[:MAX_MESSAGE_LENGTH] + "..."
    
        cleaned_commit = {
            "hash": short_hash,
            "date": date,
            "message": clean_message
        }
        
        formatted_commits_grouped.setdefault(repo, []).append(cleaned_commit)
        
    logger.debug("Formatted Commits Grouped: %s", len(formatted_commits_grouped))
    return formatted_commits_grouped

def to_prompt_str(formatted_commits:dict) -> str:    
    """
    Get the dict with cleaned commits and generates a prompt string to be used for 
    summarization
    """
    prompt_str=""

    if not formatted_commits:
        logger.warning("to_prompt_str: No formatted commits to process")
        return ""
        
    for repo, commits in formatted_commits.items():
        prompt_str += f"### {repo}\n"
        
        # Limit commits per repo to protect context window
        for commit in commits[:MAX_COMMITS_PER_REPO]:
            prompt_str += f"  - {commit['hash']} | {commit['date']} | {commit['message']}\n"
        
        if len(commits) > MAX_COMMITS_PER_REPO:
            prompt_str += f"  - ... (truncated {len(commits) - MAX_COMMITS_PER_REPO} older commits)\n"
            
        prompt_str += "\n"  # blank line between repos 

    logger.debug("to_prompt_str: Built prompt string with %s repos", len(formatted_commits))
    return prompt_str


def to_display_str(formatted_commits:dict) -> str:    
    """
    Similar to to_prompt_str but used primarily for display.
    """
    display_str=""

    if not formatted_commits:
        logger.warning("to_display_str: No formatted commits to process")
        return ""
        
    for repo, commits in formatted_commits.items():
        display_str += f"### {repo}\n"
        for commit in commits:
            display_str += f"  - {commit['hash']} | {commit['date']}\n"
            message_lines = commit["message"].split(" | ")
            for line in message_lines:
                display_str += f"    {line}\n"
        display_str += "\n"
    return display_str


def build_prompt(prompt_str:str) -> str:    
    role_instructions="""
    You are an expert technical writer.
    Your task is to generate a concise, professional weekly standup summary based on the commit history provided.
    
    Output must be structured into exactly four sections:
    
    WHAT I DID
    - Bullet points of features/fixes completed
    
    DETAILS
    - Technical details, PR numbers, or important context
    
    WHATS NEXT
    - What you plan to work on next
    
    BLOCKERS
    - Any obstacles or dependencies
    
    Rules:
    - No preamble (e.g., "Here is your summary")
    - No sign-off (no "Thanks", no name)
    - Only the four sections above
    - Keep it professional and concise
    """
    return f"{role_instructions}\n\nHere is the commit data:\n{prompt_str}"


async def summarise(prompt_str:str) -> str:
    groq_api_key = os.getenv("GROQ_API_KEY")
    if not groq_api_key:
        raise EnvironmentError("GROQ_API_KEY missing")

    async with groq.AsyncGroq(api_key=groq_api_key) as client:
        try:
            response = await client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[{"role": "user", "content": prompt_str}],
                temperature=0.3,
            )
            return response.choices[0].message.content
        except Exception as e:
            logger.error("Error during Groq summarization: %s", e, exc_info=True)
            raise
