from repo_reader import get_commits
import logging
import json

import groq
import os
from utils import load_env


logger = logging.getLogger(__name__)

def format_commits (commits:list) -> dict:
    """
    Receives a FLAT LIST of commit dicts (generated by  repo_reader.get_commits) 
    and then groups by repo, cleans messages -> returns dict
    
    Args: 
        commits (list): List of commit dicts that needs to be formatted

    Returns:
        dict object containing the cleaned commit information which will be used 
        for generating prompt and further summarize

    Raises:
        Exception: If Any errors found
    """
    #logger.debug("format_commits: Commits: %s", str(commits))

    formatted_commits_grouped = {}
    # -------------------------------------------------------------------------
    # 1. receives a FLAT LIST of commit dicts from repo_reader.get_commits
    # 2. format_commits: groups by repo, cleans messages -> returns dict
    # -------------------------------------------------------------------------
    if not commits:
        logger.warning("format_commits: No commits to format")
        return {}

    for commit in commits:
        repo = commit["repo"]

        short_hash = commit["hash"][:7]

        date = commit["date"].strftime("%Y-%m-%d")

        clean_message = " | ".join(line.strip() for line in commit["message"].splitlines() if line.strip())
    
        cleaned_commit = {
            "hash": short_hash,
            "date": date,
            "message": clean_message
        }
        
        logger.debug("Cleaned commit: %s", json.dumps(cleaned_commit, default=str))

        formatted_commits_grouped.setdefault(repo, []).append(cleaned_commit)
        
    #logger.debug("Formatted Commits Grouped: %s", str(formatted_commits_grouped))
    logger.debug("Formatted Commits Grouped:\n%s", json.dumps(formatted_commits_grouped, indent=2, default=str))
    return formatted_commits_grouped

def to_prompt_str(formatted_commits:dict) -> str:    
    """
    Get the dict with cleaned commits and generates a prompt string to be used for 
    summarization
    
    Args: 
        formatted_commits (dict): formatted commits to be used for prompt creation

    Returns:
        prompt_string (str): Prompt string to be used for summarization

    Raises:
        Exception: If Any errors found
    """
    #logger.debug("to_prompt_str: Formatted Commits: %s", str(formatted_commits))

    prompt_str=""

    if not formatted_commits:
        logger.warning("to_prompt_str: No formatted commits to process")
        return ""
        
    for repo, commits in formatted_commits.items():
        prompt_str += f"### {repo}\n"
        for commit in commits:
            prompt_str += f"  - {commit['hash']} | {commit['date']} | {commit['message']}\n"
        prompt_str += "\n"  # blank line between repos 

    #logger.debug("Prompt String: %s", prompt_str)
    logger.debug("to_prompt_str: Built prompt string with %s repos", len(formatted_commits))
    return prompt_str


def to_display_str(formatted_commits:dict) -> str:    
    """
    Similar to to_prompt_str but used primarily for dispay. Gets the dict with 
    cleaned commits and generates a renderable string 
    
    Args: 
        formatted_commits (dict): formatted commits to be used for prompt creation

    Returns:
        display_string (str): Display string to be used for summarization

    Raises:
        Exception: If Any errors found
    """
    display_str=""

    if not formatted_commits:
        logger.warning("to_display_str: No formatted commits to process")
        return ""
        
    for repo, commits in formatted_commits.items():
        display_str += f"### {repo}\n"
        for commit in commits:
            display_str += f"  - {commit['hash']} | {commit['date']}\n"
            message_lines = commit["message"].split(" | ")
            for line in message_lines:
                display_str += f"    {line}\n"
        display_str += "\n"  # blank line between repos 

    #logger.debug("Prompt String: %s", prompt_str)
    logger.debug("to_display_str: Built display string with %s repos", len(formatted_commits))
    return display_str


def build_prompt(prompt_str:str) -> str:    
    """
    Takes the pipe formatted prompt string and converts into a Prompt that will
    be sent to LLM for summarization 

    Args: 
        prompt_str (str): pipe formatted string to be used for prompt creation

    Returns:
        prompt (str): Prompt to be used for summarization

    Raises:
        Exception: If Any errors found
    """

    role_instructions="""
    You are an expert technical writer.
    Your task is to generate a concise, professional weekly standup summary based on the commit history provided.
    
    Output must be structured into exactly four sections:
    
    WHAT I DID
    - Bullet points of features/fixes completed
    
    DETAILS
    - Technical details, PR numbers, or important context
    
    WHATS NEXT
    - What you plan to work on next
    
    BLOCKERS
    - Any obstacles or dependencies
    
    Rules:
    - No preamble (e.g., "Here is your summary")
    - No sign-off (no "Thanks", no name)
    - Only the four sections above
    - Keep it professional and concise
    """
    prompt = ""

    prompt+= f"""
    {role_instructions}
    
    Here is the commit data:
    {prompt_str}
    """

    #logger.debug("build_prompt: Prompt String: %s", str(prompt_str))
    return prompt



def summarise (prompt_str:str) -> str:
    """
    Generates the summary based on the provided prompt string. 
    
    Args: 
        prompt_str (str): Prompt string to be used for summarization

    Returns:
        summary (str): Summary of the commits

    Raises:
        Exception: If Any errors found
    """        
    # 1. get GROQ_API_KEY from env, raise EnvironmentError if missing
    # 2. init groq client
    # 3. call client.chat.completions.create
    #    - model: "llama-3.3-70b-versatile"
    #    - messages: [{"role": "user", "content": prompt_str}]
    #    - temperature: 0.3
    # 4. extract response text from response.choices[0].message.content
    # 5. return it
    
    groq_api_key = os.getenv("GROQ_API_KEY")

    client = groq.Groq(api_key=groq_api_key)
    
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt_str}],
        temperature=0.3,
    )
    
    summary = response.choices[0].message.content
    #logger.debug("summarise: Summary: %s", str(summary))

    return summary  


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

if __name__ == "__main__":

    logging.basicConfig(level=logging.DEBUG)

    load_env()

    # 1. receives a FLAT LIST of commit dicts from repo_reader.get_commits
    commits = get_commits(15)
    #logger.debug("Commits: %s", str(commits))

    # 2. format_commits: groups by repo, cleans messages -> returns dict
    logger.debug("Formatted Commits: START")
    formatted_commits = format_commits(commits)
    #logger.debug("Formatted Commits:\n%s", json.dumps(formatted_commits, indent=2, default=str))

    # 3. to_prompt_str: converts dict -> compact string for LLM
    prompt_str = to_prompt_str(formatted_commits)
    #logger.debug("Prompt String: %s", str(prompt_str))

    display_str = to_display_str(formatted_commits)
    #logger.debug("Display String: %s", str(display_str))

    # 4. build_prompt: wraps string into full LLM prompt
    prompt = build_prompt(prompt_str)
    logger.debug("Prompt: %s", str(prompt))

    # 5. summarise: orchestrates 2-4, calls Groq, returns summary string
    summary = summarise(prompt)
    logger.debug("Summary: \n%s", str(summary))

    # 6. write summary to file
    with open("summary.txt", "w") as f:
        f.write(summary)
    logger.debug("Summary written to summary.txt")